jphacks/B_2121_client

goyotashi/BusinessLogic/Events/GroupEvent.swift, goyotashi/BusinessLogic/Services/GroupService.swift, goyotashi/UI/Pages/EditGroup/EditGroupReactor.swift, goyotashi/UI/Pages/EditGroup/EditGroupViewController.swift, goyotashi/UI/Pages/Group/GroupReactor.swift, goyotashi/UI/Pages/Profile/ProfileGroupList/ProfileGroupListReactor.swift
- close #118 
- グループの編集が終わった際に API を使って保存できるようにした
=> グループの編集画面の完了を押せるようにした

goyotashi/UI/Organisms/Group/GroupRestaurantCell.swift, goyotashi/UI/Pages/Group/GroupViewController.swift
=> Fix Group Screen

goyotashi/UI/Pages/AddRestaurantToGroup/AddRestaurantToGroupReactor.swift, goyotashi/UI/Pages/AddRestaurantToGroup/AddRestaurantToGroupViewController.swift, goyotashi/UI/Pages/Restaurant/RestaurantReactor.swift, goyotashi/UI/Pages/SearchRestaurant/SearchRestaurantViewController.swift
=> Add Restaurant to Group

goyotashi/UI/Molecules/CountableGroupMemberButton.swift, goyotashi/UI/Pages/CreateGroup/CreateGroupReactor.swift, goyotashi/UI/Pages/CreateGroup/CreateGroupViewController.swift
=> Fix Add Group Members

goyotashi/UI/Pages/OrganizeRestaurant/OrganizeRestaurantViewController.swift
=> Fix Organize Screen Layout

goyotashi/UI/Pages/Onboarding/OnboardingReactor.swift, goyotashi/UI/Pages/Onboarding/OnboardingViewController.swift
- close #134 
- canStartAppを追加
=> add canStartApp

goyotashi/UI/Pages/TabBar/TabBarController.swift
=> Update TabBar Selected Index at First Open

goyotashi/UI/Pages/Onboarding/OnboardingReactor.swift, goyotashi/UI/Pages/Onboarding/OnboardingViewController.swift
- 文字を編集してもテキストボックスからフォーカスが一旦外れない限りボタンが押せなくなっていたので修正した
=> オンボーディングの画面の「はじめる」ボタンの挙動を修正する

goyotashi/UI/Organisms/Profile/ProfileGroupList/ProfileGroupListCell.swift, goyotashi/UI/Organisms/Profile/ProfileGroupList/ProfileGroupListCellReactor.swift, goyotashi/UI/Pages/Profile/ProfileGroupList/ProfileGroupListReactor.swift
- close #130 
- イベント受信でリフレッシュ
- reactorが等しいかを全項目でチェック
- 一旦更新ごとに画像を全部吹き飛ばす
```
reactor.state.map { $0.groupSummary.imageUrls }
.distinctUntilChanged()
.bind { [weak self] imageUrls in
self?.clearImage()
let max = min(imageUrls.count, 6)
for index in 0 ..< max {
if index == 0 {
self?.largeImageView.kf.setImage(with: URL(string: imageUrls[0]), placeholder: R.image.dish())
} else {
self?.smallImageViews[index - 1].kf.setImage(with: URL(string: imageUrls[index]), placeholder: R.image.dish())
}
}
}
.disposed(by: disposeBag)
```
本当はこの中で0~6まで見たときに画像がなければ `R.image.dish()` とすべきだけど、`kf.setImage` の使い方わかりませんでした！
=> レストランの追加/削除でプロフィールをリフレッシュ

goyotashi.xcodeproj/project.pbxproj, goyotashi/BusinessLogic/Events/UserEvent.swift, goyotashi/BusinessLogic/Services/UserService.swift, goyotashi/UI/Organisms/Profile/ProfileHeaderView.swift, goyotashi/UI/Pages/JoinGroup/JoinGroupReactor.swift, goyotashi/UI/Pages/JoinGroup/JoinGroupViewController.swift, goyotashi/UI/Pages/Profile/ProfileGroupList/ProfileGroupListReactor.swift, goyotashi/UI/Pages/Profile/ProfileReactor.swift, goyotashi/UI/Pages/Profile/ProfileViewController.swift
=> Add Join Group Screen

goyotashi/UI/Pages/AddRestaurantToGroup/AddRestaurantToGroupViewController.swift
=> このお店を含むほかのグループの完了ボタンを削除

goyotashi/UI/Pages/Restaurant/RestaurantReactor.swift, goyotashi/UI/Pages/Restaurant/RestaurantViewController.swift
=> [feat]ほかのグループに遷移

goyotashi/UI/Organisms/Home/HomeGroupCell.swift
=> ホーム画面の画像が変

goyotashi/UI/Organisms/Home/HomeGroupCellReactor.swift, goyotashi/UI/Pages/Home/RecommendGroup/RecommendGroupReactor.swift
- close #143
- Equatable書き直した
- eventが来たら更新するようにした
=> グループの参加したあと、ホームの人数を更新する

goyotashi/UI/Pages/InviteMember/InviteMemberViewController.swift
- ユーザーの招待画面で検索バーを一旦無くした (復活させる可能性もあるのでコメントアウトした)
=> Remove search bar from invte member page

goyotashi/UI/Organisms/Profile/ProfileHeaderView.swift
=> 3点リーダーのボタンをグループに参加するボタンにする

goyotashi/UI/Organisms/Home/HomeGroupCell.swift, goyotashi/UI/Organisms/Home/HomeGroupCellReactor.swift
- close #30 
- homeのdescriptionを1行だけ表示するようにした
=> homeにdescriptionを追加

goyotashi/UI/Pages/Profile/ProfileGroupList/ProfileGroupListReactor.swift, goyotashi/UI/Pages/Profile/ProfileGroupList/ProfileGroupListViewController.swift, goyotashi/UI/Pages/Profile/ProfileViewController.swift
- close #144 
- refreshControlを追加
=> Add Refresh Control

goyotashi/UI/Pages/CreateGroup/CreateGroupViewController.swift
=> メンバーを追加 をグループの作成画面から一旦消す

goyotashi/UI/Pages/Home/RecommendGroup/RecommendGroupReactor.swift, goyotashi/UI/Pages/Home/RecommendGroup/RecommendGroupViewController.swift
- close #156 
- ホームでリフレッシュできるようにする
=> Add refreshControl to Home

goyotashi/UI/Organisms/Member/MemberCell.swift, goyotashi/UI/Pages/MemberList/MemberListViewController.swift
- close #95
- 直した
- ついでにデザイン(余白)もちょっと修正した
=> メンバーリストの制約とデザイン修正

goyotashi.xcodeproj/project.pbxproj, goyotashi/Extensions/UIImageView+Extension.swift, goyotashi/UI/Organisms/AddRestaurantToGroup/AddRestaurantToGroupCell.swift, goyotashi/UI/Organisms/Group/GroupRestaurantCell.swift, goyotashi/UI/Organisms/Home/HomeGroupCell.swift, goyotashi/UI/Organisms/OrganizeRestaurant/OrganizeRestaurantCell.swift, goyotashi/UI/Organisms/Profile/ProfileGroupList/ProfileGroupListCell.swift, goyotashi/UI/Organisms/Restaurant/RestaurantHeaderView.swift, goyotashi/UI/Organisms/Restaurant/RestaurantOtherGroupCell.swift, goyotashi/UI/Organisms/SearchRestaurant/SearchRestaurantCell.swift
- close #161 
- 高画質な画像の表示にトライする
=> Fix Displaying Restaurant Images
